### ISSUE TITLE
New Python user - issue

### ISSUE THREAD

**Issue by RVetto** [iTaxoTools/dnadiagnoser#18]
I'm having a problem where the PY file closes immediately after executing it. It doesn't happen with all the programs, though, a few work well (they open the GUI). I wonder if it's something that has to do with the Python program and not the DNAdiagnoser file.

Excuse my ignorance,
Renzo.

**Comment by necrosovereign** [comment]
Unfortunately, this is not enough information to do anything. If you could run the program in a terminal and post the output, it would be very helpful.

**Comment by necrosovereign** [comment]
@RVetto
If this is still an issue for you, please post more information, otherwise I will close the issue.
