### ISSUE TITLE
Please change once more the alignment default settings

### ISSUE THREAD

**Issue by mvences** [iTaxoTools/dnadiagnoser#28]
This time it was me to make a stupid mistake, I did not test sufficiently the performance of the pairwise alignment with different settings. I have done this now exhaustively with the new reference sequences and with several test files of different genes, and we need to change the default settings once more to make the aligner work well with "typical" datasets. I could do this myself but I prefer you do it so that I don't start modifying files in the Github repositories. 

Please change in "scores tab" the following:
gap penalty = -8

All other scores remain unchanged. Please also apply this modification to the scores.tab files in TaxI2 and TaxI3.

**Comment by necrosovereign** [comment]
I updated the default scores in all three repositories with commits to the main branches:
https://github.com/iTaxoTools/dnadiagnoser/commit/aad52d45189e7e034dfead47cdf27589a1e81bbd
https://github.com/iTaxoTools/TaxI2/commit/f1cbf79548f04d5487b2619f49bfb7eb5f24db90
https://github.com/iTaxoTools/TaxI3/commit/60549569ab0fb6bf8a832052cac6a6cda0a0f0d0
